### PR TITLE
Some PV Cleanup 

### PR DESCRIPTION
**Pull request by walkerselby**
Some cleanup, more to come eventually. 

See commit history for changes. 

Seems to function fine in-game.

### CODE REVIEW

**Comment by hannibal002** [comment]
I wanted to express my concern regarding the use of the “final” keyword in front of method parameters and variables. In my opinion, these keywords add unnecessary words to the codebase and do not serve any meaningful purpose. Currently, we only use “final” for fields in our project.

If we decide to start using the “final” keyword elsewhere, we must have a discussion and come to a consensus before implementing the change. It would be confusing to have some classes using the “final” keyword while others do not.

Therefore, I recommend that we stick to only using “final” for fields and avoid using it in front of method parameters or variables.

**Review by romangraef — APPROVED** [review]
I'm fine with both this and this without the finals

**Review by NopoTheGamer — APPROVED** [review]
final

**Review by Lulonaut — APPROVED** [review]
fine

**Pull request merged**
