### PR TITLE
Added essence shop tooltip to pv

### PR DESCRIPTION
**Pull request by NopoTheGamer**
image

Requires: https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/873

### CODE REVIEW

**Review by romangraef — APPROVED** [review]
Worked just fine, aside from the ice shop. Im assuming that is a repo issue tho

**Comment by NopoTheGamer** [comment]
> Worked just fine, aside from the ice shop. Im assuming that is a repo issue tho

whats wrong with ice?

**Comment by romangraef** [comment]
Oh, ice shop just didnt show up at all (i was using NEU/NEU-REPO/master)

**Comment by NopoTheGamer** [comment]
> Oh, ice shop just didnt show up at all (i was using NEU/NEU-REPO/master)

I may of forgotten to rename the essence

**Review by Lulonaut — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
