### PR TITLE
Rift Page in PV and several Level Page changes 

### PR DESCRIPTION
**Pull request by efefury**

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
1. 
image 
The page probably shouldn't just be blank when there is no rift data, probably an error message or something

2. 
image 
Why does the text not fit in the **text**ure 

3. 
image 
Why don't these buttons get the texture changed to pushed down like how every other button in pv works

4. 
image 
Why does this say overflow level 5 when maxed? even if you get more xp the overflow level doesn't go up so seems pretty useless

**Comment by NopoTheGamer** [comment]
5. https://hst.sh/raw/agefoxaqed 
probably shouldn't crash when looking at the leveling page

**Review by Lulonaut — DISMISSED** [review]

**Review by jani270 — DISMISSED** [review]
draw**Erorr**Message 
spelling when

**Comment by NopoTheGamer** [comment]
6. https://hst.sh/raw/porupiradi this crash probably shouldn't happen either

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]
didnt crash me how cool is that

**Pull request merged**
