### PR TITLE
Farming overlay update

### PR DESCRIPTION
**Pull request by Nubebuster**
See #730

If this change is approved then I will apply the same changes to the mining, fishing and combat overlays.

### CODE REVIEW

**Comment by Nubebuster** [comment]
If I add it to the over overlays I will make an abstract class called SkillOverlay to make the rate functions reusable.

**Comment by Nubebuster** [comment]
@romangraef 
That the counter is wrong has to do with the interpolation function and is not a new bug. This bug exists in the latest release as well. After taking a quick look at the code I have decided I do not feel like fixing it as the difference in your case for example is 0.0103443% which is not really significant. It seems like it is a rounding error in the interpolation function, though that's solely a guess of mine.

As for the XP/h, you may need to reconfigure your api key using api /new. After a minute or so it should start working.

Is the counter 0 when you farm? Could you tell me what your configuration values are? It works fine for me.

**Review by CalMWolfs — CHANGES_REQUESTED** [review]
After my testing the exp/hour worked fine so that may have been an API problem.
I have verified that the counter and cultivating are also wrong without your changes.
But I also have it showing as 0 crops and coins/second. I did not change any settings, and also reset my config to produce the same results. Playing around with the new sliders you added also did not change anything. I tested both versions on 9 of 10 crops. 
Old: 
crops_min old
Your changes:
crops_min new no settings

**Comment by Nubebuster** [comment]
Aha I didn't understand the problem before. Now I understand that the problem is that when setting the rate to per second it displays 0. That was indeed a bug. I've fixed it.

I hope my changes are now bug-free and sufficient.

**Comment by romangraef** [comment]
Could not reproduce the bugs from before, but ive also not looked too much into the causes, so they might still be present. Probably not tho.

**Pull request merged**
