### PR TITLE
 Add EnforcedConfigValues: Allow disabling options via the repo 

### PR DESCRIPTION
**Pull request by romangraef**
A severe and continuous violation of our rights to use NEUs features.

Disable features like so: 

`repo:enforced_values/*.json` (every file in that folder gets read, and only matching ones are used)
```json
{	"chatPSA":
	[	"Hello, this will be displayed in the chat upon logging into skyblock"
	]
,	"notificationPSA":
	[	"Hello, this will be displayed as a notification."
	,	"We, the NEU people ™, have disabled slot binding."
	]
,	"enforcedValues":
	[	{	"path": "slotLocking.enableSlotBinding"
		,	"value": false
		}
	]
,	"affectedVersions": [20000, 20101]
}
```
image

To be merged after #401, because it removes the caching on some things. Only last commit is relevant to this.

### CODE REVIEW

**Comment by romangraef** [comment]
On second thought i forgot to make this able to be filtered by version. Not sure if that is needed tho considering we basically never properly set the version number.

**Review by IRONM00N — DISMISSED** [review]
:D

**Comment by jani270** [comment]
Hi, i made a funny branch to test: https://github.com/jani270/NotEnoughUpdates-REPO/tree/enforced_values
So you dont have to create one

**Review by hannibal002 — DISMISSED** [review]
image
Ohh noo my most favourite feature how dare you!

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
image
shows when logging into hypixel instead of skyblock

**Comment by jani270** [comment]
> image shows when logging into hypixel instead of skyblock

yes thats the point???

**Comment by jani270** [comment]
that is from the repo a custom message

**Comment by romangraef** [comment]
> image shows when logging into hypixel instead of skyblock

Imma be honest i dont really care if it shows when logging into skyblock or when logging into hypixel. If you really do care, tell me and i can fix it.

**Comment by romangraef** [comment]
@NopoTheGamer please respond

**Comment by NopoTheGamer** [comment]
> @NopoTheGamer please respond

well all the other neu stuff shows when you join sb so

**Comment by romangraef** [comment]
> > @NopoTheGamer please respond
> 
> well all the other neu stuff shows when you join sb so

can you please clarify: does this bother you enough where you would want me to change this, or not. you are not great at communicating.

**Comment by NopoTheGamer** [comment]
yes please change :+1:

**Review by hannibal002 — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
