### PR TITLE
Make builds reproducible

### PR DESCRIPTION
**Pull request by nea89o**
This should (in theory) make it so that different people building the same git commit (with the same build properties) should get a JAR with the exact same hash. This also makes it a bit more difficult to add new dependencies. To update dependencies run `./gradlew --write-verification-metadata sha256 help`. Im making this PR in preparation for our future auto updating, which will need two people to approve a JAR in order for it to be available as an in game auto update.

### CODE REVIEW

**Review by Lulonaut — APPROVED** [review]

**Comment by NopoTheGamer** [comment]
```
2cb1b3e935cae2362240920c2d0ba0bdd3572336ff98284abd5021d71040fd59  ./NotEnoughUpdates-2.1.1+d090340.jar
e11dafcecc101b370fd262124bc0daa78d9cf7d1ba60168b77f413524ce8fc83  ./NotEnoughUpdates-2.1.1+d090340-sources-dev.jar
7b4cc4d57e192b831410ea42dfad9193782602c6234ccaafea2d2907e3eaeb55  ./NotEnoughUpdates-2.1.1+d090340-dep.jar
1485ad1f8a9d24d7e844a247c680a5485dfd00483a30121637627a6722319631  ./NotEnoughUpdates-2.1.1+d090340-dep-dev.jar
```

**Comment by Lulonaut** [comment]
```
e11dafcecc101b370fd262124bc0daa78d9cf7d1ba60168b77f413524ce8fc83  ./NotEnoughUpdates-2.1.1+d090340-sources-dev.jar
2cb1b3e935cae2362240920c2d0ba0bdd3572336ff98284abd5021d71040fd59  ./NotEnoughUpdates-2.1.1+d090340.jar
82215387ede1c11a8b9e6a5c666063a790724dba10326df75d08c6e2bc0256a0  ./NotEnoughUpdates-2.1.1+d090340-dep-dev.jar
00e93e56b1ae60b8d8c1bca0ea8a80a661c1c3ff9830cdfd8ab4fef28d068104  ./NotEnoughUpdates-2.1.1+d090340-dep.jar
```

Matches for the `.jar` and `-sources-dev.jar`, other ones are different

**Comment by nea89o** [comment]
Can someone send me the -dep.jar on discord?

**Comment by nea89o** [comment]
Actually, this might be caused by the repo thats included in the JAR.

**Comment by nea89o** [comment]
Closing due to problems with making this work with loom. Will open a new plan for signed releases in a new PR.

**Pull request closed without merging**
