### PR TITLE
Coop Soulbound kuudra drops

### PR DESCRIPTION
**Pull request by hannibal00212**
Ignoring soulbound drops (the kuudra teeth) in profit chest.

### CODE REVIEW

**Comment by efefury** [comment]
:+1: I like it!

**Comment by Ascynx** [comment]
I'm surprised no-one added it in the past. Good addition though

**Comment by NopoTheGamer** [comment]
Good addition though :+1: I like it!

**Comment by jani270** [comment]
Epic addition :+1: I really like it!

**Comment by walkerselby** [comment]
Incredible addition. 👍 I really, really like it!

**Comment by hannibal00212** [comment]
Gonna pr this again once the crowd is gone.

**Comment by Ascynx** [comment]
why

**Comment by NopoTheGamer** [comment]
wtf D:

**Comment by hannibal00212** [comment]
Admins abusing perms moment 👍

**Comment by efefury** [comment]
I am looking forward to this, I need it immediately

**Review by NopoTheGamer — APPROVED** [review]

**Comment by Mqisty** [comment]
im late but awesome addition im really looking forward to using this in my gameplay :-1:

**Review by romangraef — APPROVED** [review]

**Pull request merged**
