### PR TITLE
neuec tooltip cache

### PR DESCRIPTION
**Pull request by Ascynx**
Will try when possible to cache the tooltip to only have to use the neuec config once per item lookup. (due to how it works: it won't work with the current max enchant book and max attribute shard).

### CODE REVIEW

**Comment by Ascynx** [comment]
I'm not gonna talk about me forgetting to do shit twice in a row :skull:

**Comment by Ascynx** [comment]
image
infer found 358 issues, neat

**Comment by Ascynx** [comment]
important info is that the caching of the max book may take a few seconds.

**Review by hannibal002 — DISMISSED** [review]
My FPS go up from 95-100 to 150-160 when holding a big enchantment item with heavy presets. I love it.

**Review by NopoTheGamer — APPROVED** [review]
My FPS go up from 14-15 to 70-80 when holding a big enchantment item with heavy presets. I love it.

**Review by hannibal002 — DISMISSED** [review]

**Review by IRONM00N — APPROVED** [review]
:chart_with_upwards_trend:

**Review by romangraef — DISMISSED** [review]

**Review by hannibal002 — APPROVED** [review]

**Comment by Ascynx** [comment]
we do a smol amount of trolling

**Comment by Ascynx** [comment]
why must it remove requests :skull:

**Review by walkerselby — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
