### PR TITLE
Pet overlay progress hider, pet icon moved, and neudevtest value

### PR DESCRIPTION
**Pull request by hannibal002**
Hides the pet overlay progress if the pet is maxed out. (default off)
Dynamically move the pet display icon to better match the text.
Add /neudevtest value <value>.

### CODE REVIEW

**Review by NopoTheGamer — DISMISSED** [review]
It seems you forgot to test "show last pet" :slight_smile:

**Comment by NopoTheGamer** [comment]
image
image

I feel like the 2nd pet should be further down in the first image and uh maybe put both of them down a lil for the 2nd one

**Comment by hannibal002** [comment]
I had 2 debug lines added at the end of overlayStrings and when removing them the position for the second icon gets moved wrong. Now i readded the debug lines and it worked again. Found the solution to fix make it working without the debug lines now. xD

**Review by romangraef — CHANGES_REQUESTED** [review]
image
peeks a bit above the background

**Comment by hannibal002** [comment]
> 

If `Pet Overlay Text` is set to `Background`, the text gets rendered lower as with any other setting. The position of the icon stay at the same y value! The bug that the icon is bigger than the background for one line has nothing to do with my PR, since you can edit all the lines to only show one already.

I don't know if It's smart to move the icon position down to the text level when a background is enabled. A better solution would be to edit the background render logic, I guess.

**Review by romangraef — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
