### PR TITLE
Fix Hypixel API requests for older Java versions

### LINKED ISSUE #126: [Bug] Hypixel API requests failing on Java versions <8u141
**Mod Version:** 2.1

**Describe the bug**

Trying to make a Hypixel API request on the vanilla Java shipped with the Minecraft launcher fails. 

Hypixel recently switched certificates to use Let's Encrypt. This might be temporary, but the version of Java that Minecraft ships with in the vanilla launcher does not support Let's Encrypt certificates out of the box.

**To Reproduce**
1. Launch Minecraft from the vanilla Minecraft launcher, with the version of Java that ships with it (typically 8u51)
2. Try to make a request, /pv, etc

**Expected behavior**

The request to succeed.

### PR DESCRIPTION
**Pull request by TGWaffles**
Adds a "dirty" workaround for Java versions less than 8u141, where the ISRG Root X1 certificate was added as a supported root certificate.

Needed because Hypixel switched to using Let's Encrypt certificates (which normally require Java > 8u141), and Minecraft's vanilla launcher ships with Java 8u51 -- making it impossible to make requests to Hypixel's API now on the vanilla launcher.

This tells the client to automatically trust HTTPS connections even if it couldn't verify it.

Fixes #126

### CODE REVIEW

**Comment by romangraef** [comment]
I feel like given our update cycle we dont really need a quick and dirty fix, especially considering skytils already fixes this for us in the short term (plus hypixel could just use the cloudflare cert again, if they would bother to press like 3 buttons in their dashboard). We can still merge this, the worst thing one could do is change your cape or smth.

**Comment by Lulonaut** [comment]
Hypixel already switched back to Cloudflare

**Comment by romangraef** [comment]
im slow

**Comment by TGWaffles** [comment]
> Hypixel already switched back to Cloudflare

Amazing, better solution. Wasn't sure if they were going to, but this solves things 👍 no worries

**Pull request closed without merging**
