### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by bandarabuddhika2**

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
nice pr bro

**Comment by bandarabuddhika2** [comment]
sorry im new lol

**Comment by romangraef** [comment]
image

**Comment by romangraef** [comment]
also just use mixins?

**Comment by romangraef** [comment]
see https://git.nea.moe/nea/neuhax for an example on how to mix into neu easily

**Comment by budd9442** [comment]
okay thanks! I'll try to figure out what these mixin things are. I just didnt expect the big green button to open a pr on neu MAIN repo. github is  scary and confusing.

**Pull request closed without merging**
