### PR TITLE
Skyblock addons expect=0, and modlist config button

### PR DESCRIPTION
**Pull request by romangraef**
Synonyms for essential:

crucial, main, fundamental, imperative, important, indispensable, vital,
necessary, needed, vital, cardinal, principal, required, necessitous (oh
wow that one sounds like incestous)

### CODE REVIEW

**Comment by romangraef** [comment]
image
Make this PR a bit more full

**Comment by Wyvest** [comment]
> Synonyms for essential:
> 
> crucial, main, fundamental, imperative, important, indispensable, vital, necessary, needed, vital, cardinal, principal, required, necessitous (oh wow that one sounds like incestous)

Requisite

**Comment by MicrocontrollersDev** [comment]
> idk what any of this is but looks good to me! 👍

nahhh what is blud doing 😭😭😭

**Comment by Mqisty** [comment]
> nahhh what is blud doing sobsobsob

nea asked for a review!

**Review by IRONM00N — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
