### PR TITLE
Add option to disable the custom armor rendering

### PR DESCRIPTION
**Pull request by hannibal002**
Added option to disable the custom armor rendering for performance reasons.

### CODE REVIEW

**Comment by jani270** [comment]
Tbh, im not a big fan of this pr, this will just result in question why 1feature isnt working, just because they enabled the option that says PERFORMANCE BOOST

**Comment by hannibal002** [comment]
Move it in the dev categoriy or behind a command then? i would like to use this feature in my prism profile, as it will reduce the amount of new creation allocations, make NEU less "laggy" (you know what i mean)

**Comment by hannibal002** [comment]
missclick

**Comment by jani270** [comment]
> Move it in the dev categoriy or behind a command then? i would like to use this feature in my prism profile, as it will reduce the amount of new creation allocations, make NEU less "laggy" (you know what i mean)

Thats just even more stupid?

**Pull request closed without merging**
