### PR TITLE
Want to Complete Commission Tasks Like a Pro? This Feature is a Must-Have

### PR DESCRIPTION
**Pull request by hannibal002**
This feature allows users to view helpful tips about their current commission tasks in the Crystal Hollows. While sneaking, the mining overlay displays a short explanation of the tasks and their locations, making it easier for users to complete their commission tasks. As users become more familiar with the tasks, they will likely rely on this feature less and less over time. In the future, I also plan to implement similar tips for the Dwarven Mines.

### CODE REVIEW

**Comment by hannibal002** [comment]
Dwarven Mines:
image

Crystal Hollows:
image


Note: This does not show for commissions that have already been completed. I have not used the repository for this because I do not expect Hypixel to add new commission quests in the future (thanks to Jani for his input). The hard-coded approach allows for the region-names to have colors with a single definition.

For Crystal Hollows, it can be quite useful for newer players. For the sake of completeness, I have also included it for Dwarven Mines, although it may not be as useful there.

**Comment by efefury** [comment]
Small suggestion, wouldn't "anywhere" be better than "everywhere"?

**Comment by NopoTheGamer** [comment]
please not white text <:wahh:793520007124484148>

**Comment by walkerselby** [comment]
I think you are missing four commissions, though how you handle them is up to you. They are the tutorial commissions, which NEU displays improperly (for the obvious reason that Hypixel is lovely and used the same name)

Tutorial Commissions
--
Mithril Miner | Mine 50 Mithril Ore.
First Event | Participate in any Mining Event.
Titanium Miner | Mine 2 Titanium Ore.
Mithril Miner | Mine 150 Mithril Ore.

**Comment by romangraef** [comment]
I wonder if anyone has ever grinded hotm 5 with events as to not complete the starter commissions to see if they would fill into the third commission slot

**Comment by walkerselby** [comment]
> I wonder if anyone has ever grinded hotm 5 with events as to not complete the starter commissions to see if they would fill into the third commission slot

that's horrible, I am kinda tempted to try it. But even more painful as its basically just goblin raids, the other things require mining :skull:

**Comment by romangraef** [comment]
Mining is fine to do (i think) as long as you just never turn in the commission. So you could do don pireso. Or since the first and second commission slot have different buckets you could just only do commissions in one of the slots ig.

**Comment by hannibal002** [comment]
image
Changed the design.

And I tested the “close PR” button. It's working!

**Comment by hannibal002** [comment]
image

**Comment by hannibal002** [comment]
image
Nothing to see here

**Comment by jani270** [comment]
> image Nothing to see here

image
🔫

**Review by romangraef — COMMENTED** [review]
Maybe this is just me, but I feel like this would benefit from having an option that makes you able to view the tip on a new line instead of after the commission.

**Comment by hannibal002** [comment]
image

Mhm, unsure but still an interesting alternative

**Comment by hannibal002** [comment]
image
Now I think its actually ok-ish

**Review by romangraef — DISMISSED** [review]

**Comment by hannibal002** [comment]
Now there should be (hopefully) every missing Dwarven Mines commission as well.
Thanks Planterror (https://discord.com/channels/516977525906341928/1058762568757415969/1058762568757415969)

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
