### PR TITLE
[IMPORTANT] "Fixed" biggest neu bug in history

### PR DESCRIPTION
**Pull request by jani270**
This PR has 1 quantified lines of changes. In general, a change size of upto 200 lines is ideal for the best PR experience!

Was this comment helpful? 👍  👌  👎 (Email)

Im sure there is prob a better way to do this but i just had to do it

### CODE REVIEW

**Review by Lulonaut — APPROVED** [review]
Optimal pull request sizes drive a better predictable PR flow as they strike a
balance between between PR complexity and PR review overhead. PRs within the
optimal size (typical small, or medium sized PRs) mean:

    Fast and predictable releases to production:
        Optimal size changes are more likely to be reviewed faster with fewer
        iterations.
        Similarity in low PR complexity drives similar review times.
    Review quality is likely higher as complexity is lower:
        Bugs are more likely to be detected.
        Code inconsistencies are more likely to be detected.
    Knowledge sharing is improved within the participants:
        Small portions can be assimilated better.
    Better engineering practices are exercised:
        Solving big problems by dividing them in well contained, smaller problems.
        Exercising separation of concerns within the code changes.

What can I do to optimize my changes

    Use the PullRequestQuantifier to quantify your PR accurately
        Create a context profile for your repo using the context generator
        Exclude files that are not necessary to be reviewed or do not increase the review complexity. Example: Autogenerated code, docs, project IDE setting files, binaries, etc. Check out the Excluded section from your prquantifier.yaml context profile.
        Understand your typical change complexity, drive towards the desired complexity by adjusting the label mapping in your prquantifier.yaml context profile.
        Only use the labels that matter to you, see context specification to customize your prquantifier.yaml context profile.
    Change your engineering behaviors
        For PRs that fall outside of the desired spectrum, review the details and check if:
            Your PR could be split in smaller, self-contained PRs instead
            Your PR only solves one particular issue. (For example, don't refactor and code new features in the same PR).

**Review by hannibal002 — APPROVED** [review]
Where's the center??
image

**Comment by hannibal002** [comment]
@jani270 

It is possible that this message was generated by a bot or tool that is designed to provide feedback on pull requests (PRs) in a version control system such as Git. PRs are used to submit changes to a codebase for review and integration. It is common for teams to establish guidelines for the size and scope of PRs, and tools like this can help to ensure that PRs conform to these guidelines. The specific tool or bot that is generating this message is not clear from the information provided. It is possible that the message is being generated by a custom tool or script, or it could be a feature of a third-party application that is being used to manage the codebase.

**Review by romangraef — APPROVED** [review]
Mhmmmmm , i fucking LOVE robots, i wanna KISS robots so hard until there are NO ROBOTS left to KISS!!! i wanna put my hands around them and HUG them so TIGHTLY!!! ROBOTS like THESE that RESPECT humans so much are so LOVED by me!!!! i LOVE getting judged by a THOUGHTFUL, CAPABLE ROBOT with metrics that are FAIR and ACCURATE!! i LOVE getting my issues marked as STALE, because just because nobody has talked in a PR for 7 days means it is OBVIOUSLY FIXED!!! ROBOTS really make life better for us HUMANS!

**Pull request merged**
