### PR TITLE
Fix NPE in Level Page (v2)

### PR DESCRIPTION
**Pull request by efefury**
i wonder how many versions of this will exist

### CODE REVIEW

**Review by Lulonaut — APPROVED** [review]
One of the biggest advantages of Kotlin over Java is its built-in null-safety feature. In Java, a null reference can cause a NullPointerException at runtime, which can be hard to track down and fix. Kotlin, on the other hand, has null-safety built into its type system, meaning that the compiler ensures that null values cannot be assigned to non-nullable types.

This not only helps developers write safer code, but also makes the code easier to read and understand. With Kotlin's null-safety, developers can be more confident in their code, and spend less time debugging null-related issues.

Overall, Kotlin's null-safety feature is a significant improvement over Java, and is one of the many reasons why developers are increasingly choosing Kotlin for their projects.

**Comment by Lulonaut** [comment]
> > One of the biggest advantages of Kotlin over Java is its built-in null-safety feature. In Java, a null reference can cause a NullPointerException at runtime, which can be hard to track down and fix. Kotlin, on the other hand, has null-safety built into its type system, meaning that the compiler ensures that null values cannot be assigned to non-nullable types.
> > This not only helps developers write safer code, but also makes the code easier to read and understand. With Kotlin's null-safety, developers can be more confident in their code, and spend less time debugging null-related issues.
> > Overall, Kotlin's null-safety feature is a significant improvement over Java, and is one of the many reasons why developers are increasingly choosing Kotlin for their projects.
> 
> rewrite it in kotlin +1

While I can certainly write code in Kotlin, I believe it would be more beneficial for you to learn how to do so yourself. Learning a new programming language can be a valuable experience and can help broaden your skillset.

Fortunately, Kotlin has a very gentle learning curve, especially if you're already familiar with Java. I encourage you to take the time to learn the basics of Kotlin and try rewriting the code yourself. There are many great resources available online to help you get started, such as the official Kotlin documentation and online tutorials.

**Comment by efefury** [comment]
> > > One of the biggest advantages of Kotlin over Java is its built-in null-safety feature. In Java, a null reference can cause a NullPointerException at runtime, which can be hard to track down and fix. Kotlin, on the other hand, has null-safety built into its type system, meaning that the compiler ensures that null values cannot be assigned to non-nullable types.
> > > This not only helps developers write safer code, but also makes the code easier to read and understand. With Kotlin's null-safety, developers can be more confident in their code, and spend less time debugging null-related issues.
> > > Overall, Kotlin's null-safety feature is a significant improvement over Java, and is one of the many reasons why developers are increasingly choosing Kotlin for their projects.
> > 
> > 
> > rewrite it in kotlin +1
> 
> While I can certainly write code in Kotlin, I believe it would be more beneficial for you to learn how to do so yourself. Learning a new programming language can be a valuable experience and can help broaden your skillset.
> 
> Fortunately, Kotlin has a very gentle learning curve, especially if you're already familiar with Java. I encourage you to take the time to learn the basics of Kotlin and try rewriting the code yourself. There are many great resources available online to help you get started, such as the official Kotlin documentation and online tutorials.

Dear Lulonaut,

Thank you for your proposal regarding the usage of Kotlin. While I understand the potential benefits of this approach, unfortunately, I cannot comply with your request at this time.

I appreciate your interest in working with me, and please know that your proposal has been carefully reviewed. However, given my current priorities and resources, it's not feasible for me to move forward with this option.

I hope this doesn't deter you from proposing other ideas in the future. I value your input and would be happy to consider other proposals that align with my needs.

Thank you again for your interest in working with me, and I wish you all the best in your future endeavors.

**Comment by hannibal002** [comment]
this the right pr to convert all pv leveling stuff to kotlin? or too soon? should i wait till all other prs are done?

**Review by NopoTheGamer — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
