### PR TITLE
fixed backpacks when dont have fairy soul req

### PR DESCRIPTION
**Pull request by NopoTheGamer**

### CODE REVIEW

**Review by hannibal00212 — APPROVED** [review]

**Comment by NopoTheGamer** [comment]
hannibal can approve now??? shame im about to push a bunch of commits :trollface:

**Comment by jani270** [comment]
> hannibal can approve now??? shame im about to push a bunch of commits :trollface:

crying rn using same pr for different things

**Comment by NopoTheGamer** [comment]
project board pr go brr

**Comment by hannibal00212** [comment]
What have I done

**Comment by jani270** [comment]
> What have I done

Nothing, nopo is about to commit murder

**Comment by NopoTheGamer** [comment]
I'll move the rest to a new branch

**Comment by jani270** [comment]
thanks

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by hannibal00212 — APPROVED** [review]

**Pull request merged**
