### PR TITLE
Improve NPC shop generator

### PR DESCRIPTION
**Pull request by romangraef**
This also adds buttons that are active while in repo edit mode to export gui content.
[video](https://discord.com/channels/516977525906341928/766209671882080256/1082394173736489022)

### CODE REVIEW

**Comment by hannibal002** [comment]
can we like copy this item list scroll logic for bazaar and ah item search result box?

**Review by hannibal002 — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Comment by romangraef** [comment]
> can we like copy this item list scroll logic for bazaar and ah item search result box?

nyes. i wouldnt use this same class, but i can do something similar

**Comment by NopoTheGamer** [comment]
are we keeping the test exporter in or removing it?

**Comment by romangraef** [comment]
@NopoTheGamer removed it

**Review by NopoTheGamer — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
