### PR TITLE
Dev option to remove the junk f3-h puts on your tooltips

### PR DESCRIPTION
**Pull request by NopoTheGamer**
yes

### CODE REVIEW

**Review by hannibal002 — APPROVED** [review]
How do I press the F3 key and the H key at the same time, together??

**Comment by romangraef** [comment]
literally just?? toggle it off??

**Comment by hannibal002** [comment]
So, this PR is a true meme now? Or we gonna push it down the pipe eventually?

**Comment by romangraef** [comment]
i somehow feel like @NopoTheGamer is serious about this one

**Pull request closed without merging**
