### PR TITLE
Terrible Kotlin!

### PR DESCRIPTION
**Pull request by romangraef**
But it is as good as it gets (at least for me).

Notable features:

 * This uses a tweaker loader which allows other mods to stop us from loading kotlin in case they bundle newer versions. Ideally we would just update, but you cannot really expect users to do the same.
 * Since this introduces new tweakers, we end up having to do a bunch of work ourselves that mixin did for us (such as reenabling ourselves as a mod); I'm not sure if i caught all edge cases, but everything works, sooo.

### CODE REVIEW

**Comment by romangraef** [comment]
also @jani270 please test on windows! it should work the same there, but whenever i directly work with file paths i feel compelled to ask you about this

**Review by hannibal002 — APPROVED** [review]
looking good on windows

**Review by Lulonaut — APPROVED** [review]
give me the kotlin

**Comment by hannibal002** [comment]
Not using Kotlin is a bug!

**Review by Lulonaut — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]
game opens in dev env

**Review by DeDiamondPro — APPROVED** [review]
We love kotlang

**Pull request merged**
