### PR TITLE
Show invalid API key notification on Request failure

### PR DESCRIPTION
**Pull request by Lulonaut**
Tells the user that they should regenerate their API key and prevents the log from being spammed if they decide to not do that.

### CODE REVIEW

**Review by romangraef — COMMENTED** [review]
v cute

**Comment by NopoTheGamer** [comment]
cant wait for when people get the random 403's even when their API key is set

**Comment by DeDiamondPro** [comment]
Shouldn't we check if the api request was actually to hypixel, so we don't just show this when a random api returns 403

**Review by romangraef — DISMISSED** [review]

**Review by DeDiamondPro — DISMISSED** [review]

**Comment by efefury** [comment]
how to defeat colour vs color just name it colouzr

**Review by romangraef — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]
Color

**Review by NopoTheGamer — APPROVED** [review]
> Color

colour

**Pull request merged**
