### PR TITLE
Of course you have pronouns in pv

### PR DESCRIPTION
**Pull request by romangraef**
cutechomp

### CODE REVIEW

**Review by DeDiamondPro — DISMISSED** [review]
Looks pretty cool

**Review by Wyvest — APPROVED** [review]
BASED

**Review by pauliesnug — DISMISSED** [review]
if you dont accept this i dont love you anymore

**Comment by jani270** [comment]
> if you dont accept this i dont love you anymore

Good we will not 👍

**Comment by efefury** [comment]
> if you dont accept this i dont love you anymore

why

**Comment by romangraef** [comment]
has anyone actual objections to the pronouns in pv PR btw?

**Comment by jani270** [comment]
> has anyone actual objections to the pronouns in pv PR btw?

I think it's useless, on one side it's a profile viewer for hypixel skyblock, and pronouns have nothing to do with that, on the other side it's hover so very minor. 

So I'm not sure

**Comment by romangraef** [comment]
We can make it more prominent if you prefer. Given the huge queer population of hypixel skyblock, i don't think it is too out of place.

**Comment by DeDiamondPro** [comment]
> We can make it more prominent if you prefer. Given the huge queer population of hypixel skyblock, i don't think it is too out of place.

You should make a separate page for it and also make that page the default page, don’t forgot example sentences and giant text

**Comment by romangraef** [comment]
Diamondboy, please, i am being serious here.

**Comment by RayDeeUx** [comment]
@IRONM00N hi yes please tell jani to come to his senses, since you greenlit this when I first suggested it

**Comment by IRONM00N** [comment]
i will merge it with or without objections

**Comment by jani270** [comment]
Ery are you like dumb? Iron isn't the owner of neu. I never said that we not merging it, I just said that it has 2 sides. Fucking dumass

**Comment by kr45732** [comment]
Not like my opinion really matters but this would just be another request that will make /pv take longer to load. IMO, I would just make it toggleable and have it disabled by default. If someone has the brain to enable it, then they are probably capable of respecting other peoples' pronouns. If they can't figure out how to enable it, there's no point showing the pronouns as they probably don't care.

**Comment by romangraef** [comment]
regarding performance: this is entirely async. i will consider making it toggleable tho. on another note: I will most definitely need to add a repo feature flag for this in case we end up nuking pronoundbs servers

**Comment by RayDeeUx** [comment]
> Ery are you like dumb? Iron isn't the owner of neu. I never said that we not merging it, I just said that it has 2 sides. Fucking dumass

I never implied that Iron owned NEU, I simply pinged him since he was the one who originally greenlit my pronoun suggestion at all

don't try to steal my "jumping to conclusions" job title, unemployment rates are already bad enough rn

**Review by NopoTheGamer — APPROVED** [review]

**Comment by Ascynx** [comment]
I don't think it's a bad idea but it's probably a better idea to put it elsewhere than in pv, I don't think many will open pv to see the others pronouns.
If it were to be added it would be a better idea to put it on player name hover in chat.
At least in my opinion.

**Comment by Angry-Pineapple3121** [comment]
Unnecessary & isn't togglable / off by default

**Comment by romangraef** [comment]
> Unnecessary & isn't togglable / off by default
What do you think off /neucosmetics

**Comment by romangraef** [comment]
i don't really get the whole hate for this feature. its a lot less intrusive than random cosmetics in neu, dungeonsguide, essentials, skyclient, etc. etc. and objectively more inclusive (not walled behind paying, and probably more important to some people). im going to make it a toggle, and probably turn it off by default (the "probably" here being because i haven't finalized this PR yet, but having it off by default is what i'm planning to do), but the intense dislike for this feature is absolutely unreasonable. especially when people are calling for a poll for this one feature. NEU has lots of features being added, and some of those are controversial. none of these features get a poll. majority rule can be good, but since reading the comments from the PR (and *especially* from the various discord channels), i can safely conclude that a majority of detractors have not read the actual implementation, or my other comments on this feature, and as such continuously make mute points. that is not to say that there haven't been good suggestions, and i appreciate those and will be implementing some of those suggestions. there has been a lot of angry screaming, a lot of entitlement, a lot of declaring oneself to be "the voice of the community" on discord. i would prefer if we could keep that down in the future, and focus on actual reasonable discussion. i also have made the observation that some of the people who are against this feature, have a history of disliking pronouns and trans people as a whole. this could have of course just been coincidental, but i urge people to reconsider why they find this so objectionable. 

----

Here are some bulletpoints about technicalities (not the social aspect), in case your brain receptors cannot focus on a text that long:

 - The feature will be toggleable
 - The feature is planned to be toggled off by default
 - The feature will have a REPO based kill switch in case we nuke the pronoundb api


**please find it in your heart to be kind**

**Comment by RayDeeUx** [comment]
oof, sent to draft limbo

**Review by DeDiamondPro — APPROVED** [review]

**Review by ThatGravyBoat — APPROVED** [review]

**Review by IRONM00N — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
