### PR TITLE
add pins texture bc contributor chat confusion

### PR DESCRIPTION
**Pull request by RayDeeUx**

### CODE REVIEW

**Comment by jani270** [comment]
Literally braindead

**Comment by romangraef** [comment]
Actually retarded

(target this pr https://github.com/NotEnoughUpdates/NotEnoughUpdates/pull/118)
(we already use this texture https://github.com/romangraef/NotEnoughUpdates/blob/feature/itemshops/src/main/resources/assets/notenoughupdates/textures/gui/navigation.png)

**Comment by Ascynx** [comment]
bruh moment

**Comment by SufferingSevereBrianDamage** [comment]
i exist

**Pull request closed without merging**
