### PR TITLE
Add support for `Property` option for dropdown

### PR DESCRIPTION
**Pull request by Wyvest**

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
I got someone to test and they say it works!

image

**Comment by Wyvest** [comment]
> I mean it works, and it is somehow even worse code than the rest of this compat layer, so why not

I am pretty aware it is terrible code but it's going to be rewritten with OneConfig V1 anyways and it's a pretty critical error (the compat layer literally does not function)

**Comment by nea89o** [comment]
MoulConfig supports `Property<T>` instead of `T` transparently for all editors: https://github.com/NotEnoughUpdates/MoulConfig/blob/64d7fe23a1dcf00797e570fe3d92a3cdd30e00e5/common/src/main/java/io/github/notenoughupdates/moulconfig/processor/ProcessedOption.java#L56-L67

**Comment by Wyvest** [comment]
> MoulConfig supports `Property<T>` instead of `T` transparently for all editors: [NotEnoughUpdates/MoulConfig@`64d7fe2`/common/src/main/java/io/github/notenoughupdates/moulconfig/processor/ProcessedOption.java#L56-L67](https://github.com/NotEnoughUpdates/MoulConfig/blob/64d7fe23a1dcf00797e570fe3d92a3cdd30e00e5/common/src/main/java/io/github/notenoughupdates/moulconfig/processor/ProcessedOption.java#L56-L67)

ah. well oneconfig is a bit brittle code-wise and it would be a bit of a pain to support this (i think i would have to make a property wrapper for every config option and i don't want to do that), so ill wait till V1 for that.

For now, though, this PR should be merged as the compat layer just doesn't function rn

**Comment by nea89o** [comment]
> so ill wait till V1 for that.

Pretty sure i got told like at least a year ago that oneconfig would make those kinds of things easier soon, so i would rather still get it right in the current system. I will rewrite the entire thing myself anyway to be not neu exclusive.

**Pull request merged**
