### PR TITLE
Fix ItemEditor keeping unnecessary ExtraAttributes tags

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Made it remove the tags "attributes", "originTag", and "modifier.

### CODE REVIEW

**Comment by romangraef** [comment]
@jani270 can you sign off that these attributes arent needed?

**Comment by walkerselby** [comment]
> @jani270 can you sign off that these attributes arent needed?

Isn't the modifier just the reforge? Will this mess up features that check the reforge of items?

**Comment by jani270** [comment]
> > @jani270 can you sign off that these attributes arent needed?
> 
> Isn't the modifier just the reforge? Will this mess up features that check the reforge of items?

I dont think we have such an feature, even tho i would like to keep attributes for other mods.

**Comment by NopoTheGamer** [comment]
seems pointless

**Pull request closed without merging**
