### PR TITLE
Fixed total highest waves being included in total runs

### PR DESCRIPTION
**Pull request by GodOfProDev**
this is a fix for #507

### CODE REVIEW

**Review by hannibal002 — CHANGES_REQUESTED** [review]
Why count the highest wave and subtract them from a wrong/unnecessary number when you can simply just count the completions instead?

**Comment by GodOfProDev** [comment]
> Why count the highest wave and subtract them from a wrong/unnecessary number when you can simply just count the completions instead?

i am pretty sure the total runs include the highest wave in the API but I will test it

**Comment by jani270** [comment]
> > Why count the highest wave and subtract them from a wrong/unnecessary number when you can simply just count the completions instead?
> 
> i am pretty sure the total runs include the highest wave in the API but I will test it

Thats wrong these 2 are seperate

**Comment by GodOfProDev** [comment]
i switched to skipping the highest_wave in the map instead of passing the total highest waves

**Review by Lulonaut — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
