### PR TITLE
Dream skin

### PR DESCRIPTION
**Pull request by romangraef**
villager trades ( does not contain dream easter eggs)

### CODE REVIEW

**Comment by romangraef** [comment]
Anyway this feature only works on stranded, you need a pet and to open /pets to see the itemlist on stranded rn

**Comment by NopoTheGamer** [comment]
2.1.md :slightly_smiling_face:

**Review by DeDiamondPro — APPROVED** [review]
looks good but why the fuck is there a dream skin in the files?

**Review by NopoTheGamer — APPROVED** [review]
There is no dream skin :slightly_smiling_face:

**Review by Lulonaut — APPROVED** [review]
I don't see a dream skin

**Pull request merged**
