### PR TITLE
use optipng on all pngs

### PR DESCRIPTION
**Pull request by KTibow**
decent size reduction. it's not as much of a difference when compressed, but it's still a decent difference. most notably -64kb on space.png.

***why?***
neu is one of the largest mods out there. this is an easy way to bring the size down.
***but why?***
large mods cost more for all parties involved. they take up more storage and bandwidth. while you could say "it's not worth it", i already did all the work and all that needs to happen is a merge.

### CODE REVIEW

**Comment by Lulonaut** [comment]
Getting imgbot flashbacks

**Comment by KTibow** [comment]
i swear this is the only one

**Comment by nea89o** [comment]
@KTibow I heavily disapprove of you updating NEU in Skyclient without any input from us. Please remove that version before i entertain any more conversations with you on NEUs development.

**Review by nea89o — APPROVED** [review]
Looks generally fine? I am still careful, since image converters love to screw up things in subtle ways.

**Comment by KTibow** [comment]
I'd be surprised if that happened, optipng checks the file type and only makes lossless transforms, the only way that would happen is if the Minecraft client didn't support reduced bitsets or something

**Comment by nea89o** [comment]
> I'd be surprised if that happened, optipng checks the file type and only makes lossless transforms, the only way that would happen is if the Minecraft client didn't support reduced bitsets or something

We had issues with so called "loss less image compressors" before.

**Comment by KTibow** [comment]
What happened? How broken did it look? Did you see issues only in Minecraft or in most viewers?

**Comment by nea89o** [comment]
Will be in the next alpha, and merged if it runs without complaints in that one, please. (cc @NopoTheGamer if you do that release)

**Pull request merged**
