### PR TITLE
Override selected text when pasting in Item editor

### PR DESCRIPTION
**Pull request by Lulonaut**
title

### CODE REVIEW

**Review by NopoTheGamer — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]

**Review by romangraef — CHANGES_REQUESTED** [review]
Please consider testing your PRs.
```
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1687) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:349) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232b09]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232b09]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232b09]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232b09]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232b09]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232b09]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232b09]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232b09]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95) [start/:?]
	at GradleStart.main(GradleStart.java:24) [start/:?]
Caused by: java.lang.StringIndexOutOfBoundsException: start > end
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:855) ~[?:1.8.0_232b09]
	at java.lang.StringBuilder.replace(StringBuilder.java:262) ~[?:1.8.0_232b09]
	at io.github.moulberry.notenoughupdates.itemeditor.GuiElementTextField.keyTyped(GuiElementTextField.java:222) ~[GuiElementTextField.class:?]
	at io.github.moulberry.notenoughupdates.itemeditor.NEUItemEditor.keyTyped(NEUItemEditor.java:357) ~[NEUItemEditor.class:?]
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:578) ~[GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:534) ~[GuiScreen.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1674) ~[Minecraft.class:?]
	... 15 more
[20:25:31] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.7.0-beta.37064-for-MC-1.8.9.jar)
  DevAuthLoadingPlugin (DevAuth-forge-legacy-0.3.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 5/28/22 8:25 PM
Description: Updating screen events

java.lang.StringIndexOutOfBoundsException: start > end
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:855)
	at java.lang.StringBuilder.replace(StringBuilder.java:262)
	at io.github.moulberry.notenoughupdates.itemeditor.GuiElementTextField.keyTyped(GuiElementTextField.java:222)
	at io.github.moulberry.notenoughupdates.itemeditor.NEUItemEditor.keyTyped(NEUItemEditor.java:357)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:534)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
	at GradleStart.main(GradleStart.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:855)
	at java.lang.StringBuilder.replace(StringBuilder.java:262)
	at io.github.moulberry.notenoughupdates.itemeditor.GuiElementTextField.keyTyped(GuiElementTextField.java:222)
	at io.github.moulberry.notenoughupdates.itemeditor.NEUItemEditor.keyTyped(NEUItemEditor.java:357)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:578)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:534)

-- Affected screen --
Details:
	Screen name: io.github.moulberry.notenoughupdates.itemeditor.NEUItemEditor
```

**Comment by romangraef** [comment]
Also im pretty confident that you want to replace `textField.setCursorPosition(selectionEnd + clipboardContent.length())` with `textField.setCursorPosition(selectionStart + clipboardContent.length())` or something similar, however i cant test whether the cursor works because it just crashes whenever i past anything.

**Comment by romangraef** [comment]
After spending like 5 minutes trying to find something that *doesn't* crash me, i think it happens when pasting near a line break.

**Comment by Lulonaut** [comment]
I don't know what you did but I can't get it to crash no matter what I try.

selectionEnd is the opposite side of the selection from the cursor position, so it is effectively selectionStart (and it also sets the position correctly)

**Comment by romangraef** [comment]
I pasted near a linebreak

**Comment by Lulonaut** [comment]
Got it to reproduce, im assuming you select from left to right? I always started from the right and that's why the cursor position was basically selectionEnd. From the left however that makes no sense

**Review by NopoTheGamer — APPROVED** [review]

**Review by romangraef — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]

**Pull request merged**
