### PR TITLE
Changed the release thing from repo to normal

### PR DESCRIPTION
**Pull request by jani270**
i dont know why it was set to repo

### CODE REVIEW

**Comment by romangraef** [comment]
Wasnt it set to repo because we published our prereleases in the repo (which we now do in this repo)

**Comment by jani270** [comment]
> Wasnt it set to repo because we published our prereleases in the repo (which we now do in this repo)

Looks like it.

**Review by hannibal002 — APPROVED** [review]
After extensive and heavy testing, I am happy to confirm that these changes have no unexpected drawbacks in other parts of the codebase.

**Review by NopoTheGamer — APPROVED** [review]
Game didnt crash lgtm

**Comment by romangraef** [comment]
> > Wasnt it set to repo because we published our prereleases in the repo (which we now do in this repo)
> 
> Looks like it.

Shouldn't this link to neu/neu then instead of moul/neu

**Comment by jani270** [comment]
> > > Wasnt it set to repo because we published our prereleases in the repo (which we now do in this repo)
> > 
> > 
> > Looks like it.
> 
> Shouldn't this link to neu/neu then instead of moul/neu

the downloads banner already links to moul/neu. So i thought it would make more sense to do it the same way

**Comment by romangraef** [comment]
Can we realistically recommend people to use moulberrys downloads?

**Comment by jani270** [comment]
> Can we realistically recommend people to use moulberrys downloads?

Do we realistically think that someone even clicks on these buttons

**Comment by romangraef** [comment]
i mean you change it, might as well change it to something meaningful.

**Comment by jani270** [comment]
I think this is fine

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
