### PR TITLE
PV Refactoring

### PR DESCRIPTION
**Pull request by kr45732**
This hurt me a lot

### CODE REVIEW

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
It crashes the game if you dont have the updated repo.
Invest in Utils#showOutdatedRepoNotification please

**Comment by hannibal00212** [comment]
@SubscribeEvent
public void onTick(TickEvent.ClientTickEvent event) {
        //fancy repo check
	Utils.showOutdatedRepoNotification();
}
Any way to check the "version"/branch of repo the user is using right now?

**Review by NopoTheGamer — APPROVED** [review]
everything seemed to work

**Review by DeDiamondPro — APPROVED** [review]
I see an insane amount of pain going into this pr

**Review by DoKM — APPROVED** [review]

**Pull request merged**
