### PR TITLE
misc pv changes

### PR DESCRIPTION
**Pull request by efefury**
added percentage progress to every skill
moved slayer tier kills to the specific slayer
added essences to third page

added medals + double drops to famring skill tooltip

### CODE REVIEW

**Review by IRONM00N — APPROVED** [review]
ironmoon approved

**Review by NopoTheGamer — APPROVED** [review]

**Review by hannibal002 — CHANGES_REQUESTED** [review]
Hide percentage when already maxed level
grafik

Maybe you want to add that percentage to dungeon classes too?
grafik

And this doesn't seem right, either.
grafik

**Comment by NopoTheGamer** [comment]
> Hide percentage when already maxed level grafik
> 
> Maybe you want to add that percentage to dungeon classes too? grafik
> 
> And this doesn't seem right, either. grafik

top and bottom are intended and middle is in another pr

**Comment by hannibal002** [comment]
I would prefer a uniform format between the two PRs.
And why does the first line say “maxed” and the line below it says “100%” again? That seems to me to be unnecessary additional information that we should leave out so as not to be too confusing.

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
