### PR TITLE
add crystal hollows + dwarven mines panos

### PR DESCRIPTION
**Pull request by RayDeeUx**

### CODE REVIEW

**Review by Lulonaut — APPROVED** [review]
works and lgtm in game

**Review by jani270 — APPROVED** [review]
ew file size

**Comment by romangraef** [comment]
wdym file size

**Comment by jani270** [comment]
> wdym file size

PR adds 1273 kb to the jar and thats ew

**Review by NopoTheGamer — APPROVED** [review]
sure

**Pull request merged**
