### PR TITLE
(Maybe) Make it so prices can be more than integer limit?

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Couldn't test this in IntelliJ for some reason so I hope this works, but expect it not to since its untested.

### CODE REVIEW

**Review by hannibal002 — APPROVED** [review]

**Review by romangraef — COMMENTED** [review]
i cant see any improvement from this

**Comment by ENORMOUZ** [comment]
> 

Because getAsBigDecimal has a limit of 2,147,483,647 and ah limit was increased to 10b

**Comment by hannibal002** [comment]
Even if there shouldn't be any real improvement for the players, it's one less method call that creates one less BigDecimal object, and it's a smaller line of code. So, there is no reason not to merge, imo

**Comment by ENORMOUZ** [comment]
Yeah for now I cant find whats limiting the prices at integer limit, i checked and the https://moulberry.codes/lowestbin.json displays prices more than 2.1b fine

**Review by romangraef — APPROVED** [review]

**Pull request merged**
