### PR TITLE
reclaim neutrality

### PR DESCRIPTION
**Pull request by hannibal002**
Politics is overrated tbh

### CODE REVIEW

**Review by Ascynx — DISMISSED** [review]
So true

**Review by NopoTheGamer — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
wont github still yell at us because this isn't mouls commit

**Comment by hannibal002** [comment]
> wont github still yell at us because this isn't mouls commit

This branch is out-of-date
Update branch to merge the latest changes from the upstream repository into this branch.

Maybe use this feature?

**Comment by NopoTheGamer** [comment]
You can't commit to this branch because it is protected.

**Comment by hannibal002** [comment]
I surely can't change master directly but you or moon or moul or minikloon or notch or god can bypass this protection ig

**Comment by romangraef** [comment]
just reset your branch to mouls commit

**Comment by romangraef** [comment]
@NopoTheGamer rereview please

**Review by Lulonaut — APPROVED** [review]

**Review by Ascynx — APPROVED** [review]
pagging

**Pull request merged**
