### PR TITLE
Fix Magical Power calculation

### LINKED ISSUE #751: ProfileViewer: Magical Power wrong
Tested IGN: DexterLive
PV: https://i.imgur.com/04Pk0dQ.png
Ingame: https://i.imgur.com/qtPzi23.png

### PR DESCRIPTION
**Pull request by Lulonaut**
closes #751

Counts only one crab hat towards the magical power, even if several are present to align with the in-game calculation

### CODE REVIEW

**Comment by romangraef** [comment]
Don't sloth hats also not stack with crab hats?

**Comment by Lulonaut** [comment]
I have no idea what a sloth hat is, do you happen to have a ingame screenshot that shows that the value differs from pv?

**Comment by romangraef** [comment]
image
image
image
image

**Comment by Lulonaut** [comment]
They both start with "PARTY_HAT" so they are both filtered with this PR. According to PV (with this PR) you have 743 Magical Power, which aligns with your in game screenshot

**Review by romangraef — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
