### PR TITLE
Item Recipe and Usage keybinds in Storage Overlay

### LINKED ISSUE #475: Storage Overlay: Allow looking up recipes in the storage overlay
[Suggested by AtroxEGO](https://canary.discord.com/channels/516977525906341928/693600396492537896/1048945395465719809)

### PR DESCRIPTION
**Pull request by VixidDev**
Added item recipe and item usage keybind support in the storage overlay, also removed some unused variables. Resolves #475

### CODE REVIEW

**Comment by hannibal002** [comment]
What happens when I want to search for an item in the storage that has an "r" or "u" in the name?

**Comment by VixidDev** [comment]
> What happens when I want to search for an item in the storage that has an "r" or "u" in the name?

Then don't be hovering over an item. This will only open the recipe / usage gui if the mouse is hovering over an item in an opened backpack / ender chest.

**Comment by hannibal002** [comment]
So it does block search input while hovering over an item?

**Review by romangraef — CHANGES_REQUESTED** [review]
please check `searchBar.getFocus()` and `renameStorageField.getFocus()`

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]

**Pull request merged**
