### PR TITLE
parse tab list for skill info

### PR DESCRIPTION
**Pull request by Lulonaut**
Replaces the constant xp information endpoint polling with parsing from the tab list

also disables the MagicNumber detekt rule since I find it annoying

### CODE REVIEW

**Review by romangraef — DISMISSED** [review]

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
XP/h doesnt work on the farming overlay because the tab list says farming 51 max, but the action bar says 61%

**Comment by Lulonaut** [comment]
When a skill is maxed it's not picked up by the regex. Maybe I should make an extra regex to set the level, will check later

**Comment by Lulonaut** [comment]
Oops

**Review by jani270 — CHANGES_REQUESTED** [review]
https://hst.sh/raw/yayubehovo

**Review by romangraef — APPROVED** [review]
I dont approve of removing the magic number rule, but i feel like complaining about that would be an uphill battle

**Review by NopoTheGamer — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Review by romangraef — APPROVED** [review]

**Pull request merged**
