### PR TITLE
Only render active overlays in location editor

### LINKED ISSUE #670: OverlayManager: Toggle for disabled overlays
Add a toggle to disable disabled overlays in the GUI Locations editor

### PR DESCRIPTION
**Pull request by Lulonaut**
Checks if the overlay is actually enabled in the config before rendering it in the location editor.

closes #670

### CODE REVIEW

**Review by romangraef — APPROVED** [review]

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
image
This pr makes this funky box show on the drill fuel bar

image
Doesnt show on master

**Comment by NopoTheGamer** [comment]
> Pretty sure that box is intentional

well I made it and i didnt intend for it to show

**Comment by Lulonaut** [comment]
I think just having a random bar is not as useful as having the box there

**Review by NopoTheGamer — APPROVED** [review]
if you say so

**Pull request merged**
