### PR TITLE
fixed /apinew bug

### PR DESCRIPTION
**Pull request by hannibal00212**
This is an annoying bug that happened to the best of us. Hopefully, not anymore. :)

### CODE REVIEW

**Comment by jani270** [comment]
☠️

**Comment by hannibal00212** [comment]
Who doesn't want support for "/a p i n e w" and "/ApInEwIsNoTwOrKiNg" the same time?

**Review by romangraef — CHANGES_REQUESTED** [review]
Since we are blocking potentially intended user behaviour, i feel like we should just show a chat message to the user (while still passing the original command on to hypixel): 

```
You just executed /apinew. I think you meant to execute [/api new].
```

This is kind of bad if hypixel ever decided to change the /api new command.

**Comment by hannibal00212** [comment]
image

**Review by romangraef — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Review by DeDiamondPro — APPROVED** [review]

**Pull request merged**
