### PR TITLE
Fixed ConcurrentModificationException in Texture Manager

### PR DESCRIPTION
**Pull request by IlmarsXd**

### CODE REVIEW

**Comment by hannibal002** [comment]
Maybe clarify that this does not fix a neu error, but rather a compatibility problem with 5zig

**Comment by IlmarsXd** [comment]
Done

**Review by Lulonaut — APPROVED** [review]

**Comment by nea89o** [comment]
I don't really see how NEU is causing an incompatibility here. We don't change any behaviour that interacts with listTickables. I am also kind of suspicious of people use synchronized collections since it can be quite easily used to mask concurrency issues when used incorrectly (iterating without locking)

**Comment by IlmarsXd** [comment]
The incompatibility comes from 5zig (possibly essentials but cannot confirm) by loading custom cosmetics during the AbstractClientPlayer initialization.
NEU profile viewer loads the player in the first page (basic page) on a separate thread, therefore also running the 5zig code that adds an element in listTickables and causing the ConcurrentModificationException.
If this PR isnt the fix you wanted, you can suggest a better fix for this issue, as I am not sure what else could be done

**Comment by nea89o** [comment]
Oh, no, that makes sense. I was just confused because of the other mixin already sitting in this file. Kind of makes me wish NEU used one mixin file per logical patch instead of one mixin file per class. I would like it if you could add the info about the async player init in pv, but this looks good to me otherwise.

**Comment by IlmarsXd** [comment]
Done

**Review by nea89o — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
