### PR TITLE
Change @Redirect to @ModifyArg

### PR DESCRIPTION
**Pull request by romangraef**

### CODE REVIEW

**Review by Lulonaut — APPROVED** [review]

**Comment by NopoTheGamer** [comment]
Doesn't compile lol

**Comment by romangraef** [comment]
@xef5000 apparently does not compile

**Comment by hannibal002** [comment]
[ Make it compile-able ](https://gist.github.com/hannibal002/bc55e11392b5a250f8de174ec998f987)

**Comment by romangraef** [comment]
Superseded by https://github.com/NotEnoughUpdates/NotEnoughUpdates/pull/693, so that i can make actual changes

**Pull request closed without merging**
