### PR TITLE
cleaned up neu overlay

### PR DESCRIPTION
**Pull request by efefury**
lmk if there's any bugs, testing appreciated

### CODE REVIEW

**Comment by hannibal00212** [comment]
Looks fine to me - haven't tested yet

**Review by Lulonaut — DISMISSED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by romangraef — APPROVED** [review]

**Comment by hannibal00212** [comment]
Looks still fine to me - no real testing done since no pc

**Review by Lulonaut — APPROVED** [review]

**Review by romangraef — DISMISSED** [review]

**Review by Lulonaut — CHANGES_REQUESTED** [review]
Submit review

**Comment by jani270** [comment]
> Submit review

so true

**Review by romangraef — DISMISSED** [review]

**Review by Lulonaut — DISMISSED** [review]
Revert "FHJNX GHD"

**Review by NopoTheGamer — CHANGES_REQUESTED** [review]
"FHJNX GHD"

**Review by Ascynx — CHANGES_REQUESTED** [review]
https://cdn.discordapp.com/attachments/832652653292027904/1016308355574280262/2022-09-05_13-26-08.mp4 where did my fps go (only when patcher is there / with equipment hud on) and where did the cache go

**Review by NopoTheGamer — APPROVED** [review]

**Review by Ascynx — APPROVED** [review]

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
