### PR TITLE
fix armor hud being 1px off

### PR DESCRIPTION
**Pull request by NopoTheGamer**
omg

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
cringer

**Review by IRONM00N — APPROVED** [review]
very important fix

**Comment by IRONM00N** [comment]
why has no one reviewed this?

**Comment by jani270** [comment]
> why has no one reviewed this?

Because its a shitty change that noone likes

**Comment by IRONM00N** [comment]
seems fine to me

**Comment by efefury** [comment]
> why has no one reviewed this?

most pointless change in the world, it's so unnecessary

**Comment by jani270** [comment]
> seems fine to me

just no

**Comment by IRONM00N** [comment]
> > why has no one reviewed this?
> 
> Because its a shitty change that noone likes, you just make the feature worse

I didn't make anything worse

**Comment by jani270** [comment]
> > > why has no one reviewed this?
> > 
> > 
> > Because its a shitty change that noone likes, you just make the feature worse
> 
> I didn't make anything worse

That "you" wasnt against you personally, it was a form of us in neu terms

**Review by IRONM00N — CHANGES_REQUESTED** [review]
make less shit

**Comment by jani270** [comment]
so true

**Review by DeDiamondPro — APPROVED** [review]

**Comment by jani270** [comment]
wtf no

**Comment by DeDiamondPro** [comment]
> wtf no

No no this is very important and has to be merged ASAP!!!!

**Comment by jani270** [comment]
> > wtf no
> 
> No no this is very important and has to be merged ASAP!!!!

image

**Comment by IRONM00N** [comment]
he he

**Pull request closed without merging**
