### PR TITLE
more code clean up

### PR DESCRIPTION
**Pull request by IRONM00N**

### CODE REVIEW

**Review by nopothegamer — APPROVED** [review]
doesnt look like you broke anything

**Comment by DeDiamondPro** [comment]
I'm having a Christmas party rn I don't have the time to check 2k lines changed

**Comment by jani270** [comment]
Im too small brain to understand what you are doing here so my review would be not helpful

**Review by DeDiamondPro — APPROVED** [review]
Looks good! Also dear iron, please unblock me from bushbot.

**Pull request merged**
