### PR TITLE
Move to gradle version 7.6

### PR DESCRIPTION
**Pull request by Scherso**

### CODE REVIEW

**Comment by Scherso** [comment]
I don’t believe dependabot automatically does this, so I’m gonna be dependabot today.

**Comment by romangraef** [comment]
We don't really use dependabot. The versions of things we currently use are mostly fine for our needs, and in fact some dependencies are intentionally fixed to an older version (for example mixins), to prevent trans dependency mismatches that can only occur in a standard minecraft FML configuration and not in a devenv (and are therefore hard to reproduce for most devs and especially dependabot).

I also don't really see a point in upgrading the gradle version, since we cannot/do not make use of any of the new features (and there are not really any performance benefits). Both of these issues stem from the atrociously old version of loom we depend on (I am very slowly working on an alternative, but it is not ready yet).

**Comment by Scherso** [comment]
Adding support for 7.6 means adding support for Java language version 19, in which, the new language features would be totally usable with the current Arch Loom version this project, `0.1.3`.  Although you still cannot run a client without the use of the `1.8.0` versions of the JDK.

Also upgrading Gradle versions, such as this for example comes with 150 new fixes to bugs, according to [Gradle's changelog](https://docs.gradle.org/7.6/release-notes.html).
> 150 issues have been fixed in Gradle 7.6.

**Comment by romangraef** [comment]
We can't really make use of Java 19 language features since we need to compile to an older platform anyway (and our buildscripts are in kotlin which does not have any bonuses from targeting higher JVM versions). There isnt really anything blocking this, but it's just a whole nothing update for us and feels like updating just for updatings sake.

**Review by romangraef — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]
skyblock player brain -> number get bigger

**Comment by Scherso** [comment]
so real

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
