### PR TITLE
Make Fairy souls progress track for each profile

### PR DESCRIPTION
**Pull request by Lulonaut**
This will convert the old config file to the new version and keep tracking fairy soul progress for each profile independently.

### CODE REVIEW

**Comment by nopothegamer** [comment]
Wouldnt this break the config option in /neu ?

**Review by nopothegamer — APPROVED** [review]

**Comment by IRONM00N** [comment]
I will review this properly when i have some time.

**Review by IRONM00N — APPROVED** [review]
looks good to me, I will merge once someone else looks at this too

**Review by nopothegamer — APPROVED** [review]
looks good!

**Review by IRONM00N — APPROVED** [review]

**Pull request merged**
