### PR TITLE
Update BazaarPriceWarning.kt for easier reading

### PR DESCRIPTION
**Pull request by ThatGuyWhomAsked**
Makes it more readable hopefully

### CODE REVIEW

**Comment by Lulonaut** [comment]
That's not how this works

**Comment by Madeleaan** [comment]
§1String is my favourite java type

**Comment by MisterCheezeCake** [comment]
> §1String is my favourite java type
It should be `§58String` since the string is 58 characters long. §Number is how you specify string length in Java.

**Comment by Ascynx** [comment]
image
LGTM

**Pull request closed without merging**
