### PR TITLE
[Calculator] Add exponent operator and % postfix

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by romangraef** [comment]
Can you also do `%` postfix

**Comment by u9g** [comment]
> Can you also do `%` postfix

Yup, done. 
image
image

**Review by hannibal002 — APPROVED** [review]

**Comment by NopoTheGamer** [comment]
Can we add some limit on ^? after like 8 digits my game just blows up 
I know you don't really need to be doing anything to the power of 10000 trillion but I know some kid will annoy me in 3 months saying their game crashed

**Comment by hannibal002** [comment]
> Can we add some limit on ^? after like 8 digits my game just blows up I know you don't really need to be doing anything to the power of 10000 trillion but I know some kid will annoy me in 3 months saying their game crashed

Maybe put the whole calculation function into a separate thread and give it a lifetime of 200ish ms?

**Review by romangraef — COMMENTED** [review]
How does this handle fractional values (crash, rounding, truncating) im leaning towards crashing, actually.

**Review by IRONM00N — COMMENTED** [review]
would it be possible to make `**` work for exponents too or does the parser only work with single-character operators?

**Comment by u9g** [comment]
image

Added:
- Only accept powers <1000 (Nopo's suggestion)
- Only accept non-decimal powers (romangraef's suggestion)
- Allow using ** instead of ^ (IRONM00N's suggestion)

**Review by NopoTheGamer — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Review by IRONM00N — APPROVED** [review]
lgtm!

**Pull request merged**
