### PR TITLE
Add support for all xp pets

### PR DESCRIPTION
**Pull request by NopoTheGamer**
Requires https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/878
Fixes https://github.com/NotEnoughUpdates/NotEnoughUpdates/issues/461

I have not tested this, but its probably correct

### CODE REVIEW

**Comment by hannibal002** [comment]
As far as my 2 minutes research goes, only the bingo pet is "all-exp". Is this correct? We need to wait for the next bingo to test this pr then

**Review by romangraef — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Comment by hannibal002** [comment]
Will approve on February, 1st.

**Comment by NopoTheGamer** [comment]
> Will approve on February, 1st.

image
I don't really want to wait 12 months

**Comment by hannibal002** [comment]
I start with opening the pet's menu to see my pet is at 5% progress
image

Now I break wheat until I have 6% progression
image

I open the pet's menu again to update with the real exp values:
image

And see that the real progress was only 0.8pp, not 1pp.
So, the PR resolves the problem I had before (the real update happens when neu pet display shows only 40-50% progress) but it's still not totally exactly.
Would approve if you're all sure it's the best we can get at calculating this.

**Review by Lulonaut — APPROVED** [review]

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
