### PR TITLE
Hide Hypixel reforge stats in Reforge Stone lore

### PR DESCRIPTION
**Pull request by Lulonaut**
This hides the stats for Legendary items that Hypixel adds to the reforge stone lore (if enabled), because you can already see this info with another neu feature.

### CODE REVIEW

**Review by romangraef — DISMISSED** [review]
LGTM, we really need to move more code out of the NEUEventListener tho

**Review by NopoTheGamer — APPROVED** [review]

**Comment by NopoTheGamer** [comment]
2.1.md :slightly_smiling_face:

**Review by romangraef — APPROVED** [review]
exceptional work on that markdown file

**Review by NopoTheGamer — APPROVED** [review]
It was marked down

**Review by jani270 — APPROVED** [review]
😎

**Pull request merged**
